server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/smart_family?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 618731zls
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 618731zls
    jedis:
      pool:
        max-active: 20
    lettuce:
      shutdown-timeout: 1000
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    publisher-returns: true
    publisher-confirm-type: correlated #必须配置这个才会确认回调
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动确认
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 3 #启动消费者最大数量
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5
          stateless: false
          #时间策略乘数因子
          multiplier: 1
          initial-interval: 1000ms
          max-interval: 10000ms
        default-requeue-rejected: true
logging:
  config: classpath:logback.xml
  file:
    path: F:\ideawork\log

calarck:
  base_image_path: /calarck/images/defalult.jpg
  local_service_address: E:\uploadData\calarck\images
#需要配置mybatis才能使用自定义mapper
mybatis-plus:
  mapper-locations: classpath*:com/example/family/**/mapper/xml/*.xml
  type-aliases-package: com.example.family.*.entity